version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9-alpine3.16
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt"}}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install make
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt"}}
      - run:
          name: run lint
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install make
            make lint
workflows:
  default-workflow:
    jobs:
    - build